---
groups:
  - title: "ğŸ’¥ Breaking changes"
    regexp: '^.*?(feat|chore|fix)!(?:\(\w+\))?!?: .+$'
    order: 50
  - title: "ğŸš€ New Features"
    regexp: '^.*?feat(:\(\w+\))?: .+$'
    order: 100
  - title: "ğŸ“¦ Dependency updates"
    regexp: '^.*?chore(:\(\w+\))?: .+$'
    order: 300
  - title: "âš ï¸ Security updates"
    regexp: '^.*?sec(:\(\w+\))?: .+$'
    order: 150
  - title: "ğŸ› Bug fixes"
    regexp: '^.*?(fix|refactor)(:\(\w+\))?: .+$'
    order: 200
  - title: "ğŸ”¨ Refactoring"
    regexp: '^.*?refactor(:\(\w+\))?: .+$'
    order: 250
  - title: "â™»ï¸ Revert changes"
    regexp: '^.*?revert(:\(\w+\))?: .+$'
    order: 250
  - title: "ğŸ“š Documentation updates"
    regexp: '^.*?docs(:\(\w+\))?: .+$'
    order: 400
  - title: "ğŸ—ï¸ Build process updates"
    regexp: '^.*?(build|ci)(:\(\w+\))?: .+$'
    order: 400
