---
groups:
  - title: "ğŸ“¦ Dependency updates"
    regexp: '^.*?chore(?:\(\w+\))?: .+$'
    order: 300
  - title: "ğŸš€ New Features"
    regexp: '^.*?feat(?:\(\w+\))?: .+$'
    order: 100
  - title: "âš ï¸ Security updates"
    regexp: '^.*?sec(?:\(\w+\))?: .+$'
    order: 150
  - title: "ğŸ Bug fixes"
    regexp: '^.*?(fix|refactor)(?:\(\w+\))?: .+$'
    order: 200
  - title: "ğŸ“š Documentation updates"
    regexp: '^.*?docs?(?:\(\w+\))?: .+$'
    order: 400
  - title: "ğŸ—ï¸ Build process updates"
    regexp: '^.*?(build|ci)(?:\(\w+\))?: .+$'
    order: 400
